### ISSUE TITLE
[Windows] If there is a close handler and the states() stream is not listened then the window is never closed

### ISSUE THREAD

**Issue by CarlosNihelton** [ubuntu-flutter-community/yaru_window.dart#29]
It's not clear that one has to listen to the `YaruWindow.states()` stream in order to allow the installed close handlers to work. The fact is that the underlying `WindowManager` only gets a listener assigned if the `YaruWindow` callers subscribe to the `states()` stream.

https://github.com/ubuntu-flutter-community/yaru_window.dart/blob/main/packages/yaru_window_manager/lib/src/window_manager.dart#L168-L174

But nothing prevents one to install a close handler without listening to the stream. There is no proper way to enforce that because those are distinct operations that have no specific order to happen. But, the moment one adds a close handler, the window can no longer be closed, because the `window_manager` plugin sets an internal flag to prevent the window from being closed, only resettable if all the assigned close handlers return true. If one never subscribes to the `states()` stream the `_handleClose` method is never closed, so although the window is rendered as closable, in practice the `WM_CLOSE` events are captured, the close handlers are never called and the window never closes.

https://github.com/ubuntu-flutter-community/yaru_window.dart/blob/main/packages/yaru_window_manager/lib/src/window_manager.dart#L208-L216

IIUC, the Linux implementation has those two features disconnected. The way to achieve this behavior on the `YaruWindowManager` implementation would be to assign a `WindowListener` unconditionally, disregarding whether the stream has listeners or the `_onCloseHandlers` is not empty. Like this:

```diff
index ed8997f..01d9133 100644
--- a/packages/yaru_window_manager/lib/src/window_manager.dart
+++ b/packages/yaru_window_manager/lib/src/window_manager.dart
@@ -160,14 +160,15 @@ extension _YaruWindowManagerX on WindowManager {
 }

 class _YaruWindowListener extends WindowListener {
-  _YaruWindowListener(this._wm);
+  _YaruWindowListener(this._wm) {
+    _wm.addListener(this);
+  }

   final WindowManager _wm;
   StreamController<YaruWindowState>? _controller;

   Stream<YaruWindowState> states() async* {
     _controller ??= StreamController<YaruWindowState>.broadcast(
-      onListen: () => _wm.addListener(this),
       onCancel: () => _wm.removeListener(this),
     );
     yield* _controller!.stream;
```

A second option would be calling `setPreventClose(true)` when the stream is listened, instead of when close handlers are added. There will be still possible for one to add close handlers that will have no effect, but at least there will be no surprising immortal windows and that aspect can be warned through documentation.

Another option would be modify the `addCloseHandler()` method to check if the controller has been assigned and, if not, do its initialization, and then listen to its stream, thus ensuring that there will be a `WindowListener` assigned if there is somebody interested in at least the close event. This way would even avoid surprises because once a close handler is installed, it will be invoked for sure, but looks a bit weird, IMHO, because what's the stream subscription's `onData` method should do?

For the sake of completeness, the `window_manager` `setPreventClose()` method is not exposed through `YaruWindow`, but only touched in those two two specific places: `addCloseHandler()` and `_handleClose()`

I'd be happy to push a PR with the appropriate fix, but I think some guidance is needed before I start implementing anything,

---

Here's a reproducer `main.dart`:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:yaru_window/yaru_window.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await YaruWindow.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late YaruWindowInstance window;
  StreamSubscription<YaruWindowState>? _subs;
  @override
  void initState() {
    super.initState();
    window = YaruWindow.of(context);
    window.onClose(() {
      // (1) this line ...
      debugPrint('Quitting! Bye!');
      return true;
    });
    //_subs = window.states().listen((event) => debugPrint(event.title));
    // (3) unless we uncomment the line above.
  }

  @override
  void dispose() {
    _subs?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () => quit(),
          child: const Text('Quit Now'),
        ),
      ),
    );
  }

  Future<void> quit() async {
    return window.close(); // (2) prevents this one from working,
  }
}

```

**Comment by jpnurmi** [comment]
Nice catch and great analysis! Would it be an option to have two separate listeners? One listener for window closing and another for state changes, to keep the features de-coupled?

**Comment by CarlosNihelton** [comment]
> Would it be an option to have two separate listeners? One listener for window closing and another for state changes, to keep the features de-coupled?

I don't see anything in the `window_manager` codebase preventing us from doing that, so I'll put together a PR implementing two `WindowListener`'s and unconditionally subscribing the on-close-listener one.
